### ISSUE TITLE
[FEAT] 투표 결과 페이지, 투표 현황 페이지에서 다음 라운드로 넘어가는 기능

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#106]
## Description 💭
방장이 다음 또는 결과 확인을 누르면 모든 참여자가 투표 결과 페이지 또는 투표 현황 페이지에서 게임의 다음 라운드로 넘어갈 수 있다.

## TODO ✅
- [ ] 모든 유저는 poling으로 서버에 현재 라운드를 보내고 응답으로 라운드가 끝났는지를 받는다.
- [ ] 방장만 다음 또는 결과 확인 버튼이 활성화 된다.
- [ ] 방장이 다음 버튼을 누르면 다음 라운드로 넘어가기 api를 호출한다.
- [ ] 라운드가 끝났는지 응답의 여부에 따라 게임 페이지로 라우팅한다.
- [ ] 해당 기능을 테스트하기 위해 msw를 연결한다.
