### ISSUE TITLE
[REFACTOR] timeLimit을 ms 단위에서 s 단위로 변경한다.

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#108]
## Description 💭
timeLimit을 ms 단위에서 s 단위로 변경한다.

## TODO ✅
- [ ] RestDocs 설정값 변경
- [ ] sql 파일 설정값 변경
- [ ] test코드 설정값 변경

### Reference 🔎
https://www.notion.so/ghenmaru/timeLimit-e4b95969a8654d8e93959eb9c9381f23?pvs=4
