### ISSUE TITLE
[FEAT] 주제, 선택지 조회 API 상태 검증 및 응답값 변경

### ISSUE THREAD

**Issue by jhon3242** [woowacourse-teams/2024-ddangkong#113]
## Description 💭
V3 에 맞게 추가된 라운드 시간, 방 상태 등애 맞게 주제 선택지 조회 API를 수정한다.

## TODO ✅
- [ ] Room과 currentRound로 RoomContent 조회 시 없으면 예외를 발생시킨다.
- [ ] 주제, 선택지 조회시 현재 방 상태가 `PROGRESS`인지 검증한다.
- [ ] 방 설정 시간을 응답에 추가한다.
