### ISSUE TITLE
[FEAT] Logging 적용

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#144]
## Description 💭
Logback을 사용한다.

## TODO ✅
- [x] Presentation Layer Logging (AOP)
- [x] DEBUG level 파일 적재
- [x] xml 설정
- [x] ERROR level 디스코드 notification
