### ISSUE TITLE
[FEAT] Prodction 환경 구축

### ISSUE THREAD

**Issue by leegwichan** [woowacourse-teams/2024-ddangkong#176]
## Description 💭

실제 배포를 위해 Prodction 환경 구축

## TODO ✅

- [ ] Production 환경 구성 논의
- [ ] 의논된 구성에 맞추어 EC2 띄우기
- [ ] Ngnix, Server Application, Database를 설정 후 정상 작동 확인

### Reference 🔎

타칸, 커찬 서버 구축 기록
https://www.notion.so/ghenmaru/Prod-ca85648750bc49eb9da8463bcf241950
