### ISSUE TITLE
[REFACTOR] 테이블 구조 변경

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#178]
## Description 💭
논의된 여러 검증 추가에 따라 테이블 구조 변경이 불가피하다.
4차 스프린트 개발 이전에 선행되어야 한다.

### 게임이 모두 끝나고 방이 더 이상 존재할 이유가 없을 때
현재 구현의 연관관계는 방 삭제 시 멤버 N개, 투표 N개가 모두 삭제되어야 한다.
이 때 투표는 삭제되지 않아야 하기 때문에 방 투표, 전체 투표 테이블로 분리한다.

## TODO ✅
- [x] ERD 수정
- [x] 연관관계 수정에 따라 코드 리팩토링
- [x] 방 초기화 시 방 투표 삭제, 전체 투표에 저장
- [x] 중복 투표 검증
  - 같은 옵션에 투표 중복 (따닥) -> unique 제약
  - 같은 컨텐츠의 옵션에 투표 -> 이중 투표 확인
