### ISSUE TITLE
[REFACTOR] exception 코드, 클래스 추가

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#181]
## Description 💭
비즈니스 정책에서 발생하는 예외는 **예외 코드**를 정의하여 프론트엔드와 협업하는 것으로 논의되었다.

## TODO ✅
- [x] 추상 클래스 구현
- [x] 예외 코드 enum 구현
- [x] 예외 클래스 구현 및 현재 예외를 던지는 곳에 클래스 반영
- [x] ExceptionHandler 수정
- [x] RestDocs 예외코드 작성
