### ISSUE TITLE
[FEAT] 투표 현황 페이지에서 투표를 하지 않은 기권자를 보여주는 기능

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#199]
## Description 💭
투표 현황 페이지에서 투표를 하지 않은 기권자를 보여준다.

## TODO ✅
- [x]  기권자 항목 추가
- [x] 투표 현황 페이지 ui 깨지는 것 수정
- [ ] 투표 현황 페이지 땅콩 이모지 -> 땅콩 아이콘으로 교체
