### ISSUE TITLE
[REFACTOR] polling api에서 방장 정보를 함께 응답하도록 변경

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#204]
## Description 💭
```jsonc
{
        // 기존 response body
        ,
	"master" : {
		"memberId" : 1,
		"nickname" : "프콩"
	}
}
```

## TODO ✅
- [x] 대기방 정보 조회 api `/api/balances/rooms/{roomId}` 게임 시작 여부 polling
- [x] 투표 완료 여부 조회 api `/api/balances/rooms/{roomId}/contents/{contentId}/vote-finished` 투표 완료 여부 polling
- [x] 라운드 종료 여부 조회 api `/api/balances/rooms/{roomId}/round-finished?round={round}` 라운드 종료 여부 polling
