### ISSUE TITLE
[FEAT] 방 설정 API 검증 로직 수정 및 구현

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#215]
## Description 💭
- [x]  **timeLimit** 값 검증 ***(추후 PR들이 머지되면 도메인 객체로 분리하는 리팩토링 필요(현재 Room 객체에서 관련 로직 관리중))***
- [x]  **timeLimit** 이 `5초`/`10초`/`15초` 중 하나인지 검증
    - [x]  Default 값은 10초
- [x]  **totalRound** 값이 `3` 이상 `10` 이하인지 검증  ***(추후 PR들이 머지되면 도메인 객체로 분리하는 리팩토링 필요(현재 Room 객체에서 관련 로직 관리중))***

## TODO ✅
- [ ] 
- [ ] 

### Reference 🔎
https://www.notion.so/ghenmaru/API-608f1d28634f47c4b9ade502d147b325?pvs=4
