### ISSUE TITLE
[REFACTOR] Dev환경 SSL/TLS 인증서 Nginx로 이전

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#234]
## Description 💭
SSL/TLS 인증서 자동 갱신 기능 구현을 위해 SpringBoot 에서 관리하던 인증서 Nginx로 이동
현재 Git Actions Secrets에서 관리하는 상태로는 권한 이슈로 인해 Secrets 값을 Github API로 변경할 수 없어 자동 갱신 불가능

## TODO ✅
- [x] application-dev.yml 의 ssl 관련 구성 제거
- [x] dev-cd 파이프라인에서 SSL/TLS 인증서 삽입 과정 제거
- [x] dev-cd 파이프라인에서 Spring Docker Container 포트포워딩 8080:8080 으로 변경
- [x] dev 서버에 Nginx 설정
- [x] dev 서버에 SSL/TLS 인증서 자동 갱신 동작 설정
