### ISSUE TITLE
[FIX] msw 테스트 코드 실행 오류 수정

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#25]
## Description 💭
- 브라우저 상에서는 msw가 잘 동작하지만 테스트 코드에서 API를 mocking하는 msw/node 오류 발견
- 테스트 코드에서 API 호출 시 mocking 적용 안됨 (data -> undefined, isSuccess -> false)

## TODO ✅
- [x] API 호출하는 테스트 코드 작성 후 테스트 실행
- [x] msw/node 환경에서의 mocking 구축
- [x] babel-loader로 css prop 인식 못하는 오류 해결

### Reference 🔎
https://mswjs.io/docs/integrations/node
https://mswjs.io/docs/migrations/1.x-to-2.x#requestresponsetextencoder-is-not-defined-jest
