### ISSUE TITLE
[REFACTOR] 닉네임 설정 화면 UX 개선 및 리팩토링

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#252]
## Description 💭
론칭 페스티벌과 UT에서 얻은 사용자 피드백을 반영하여 닉네임 설정 화면 UX 개선 및 리팩토링

## TODO ✅
- [x] 닉네임 글자수 12자로 제한
- [x] 닉네임 Enter로도 방 생성 및 참여 가능
- [x] 잘못된 uuid로 판단하는 로직 수정
- [x] 불필요한 joinable 요청 제거

### Reference 🔎
https://ghenmaru.notion.site/f4473ab5887d43b3a64d4d30a94de0ab?pvs=4
