### ISSUE TITLE
[FEAT] 대기방 UI 수정 및 런칭 데이 피드백 반영 

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#274]
## Description 💭

런칭 데이에서 받은 피드백 반영

## TODO ✅
- [x]  닉네임 입력 시, 화면이 확대되지 않도록 한다. 
- [x] 초대하기 버튼 UI 수정
- [x] 라운드와 타이머를 카테고리와 함께 표시
- [x] 총 인원 글씨 키우기, 버튼에 참여 인원 표시 
- [x] 닉네임 페이지에서 키보드가 올라가면 "참가 버튼"도 같이 올라간다. 
- [x] 카테고리 영역 클릭 시 카테고리 변경 가능 
- [x] 나가기 버튼 클릭 시 최종 확인 모달 띄우기 
- [x] 모달 on 되면 없어졌던 스크롤이 다시 생기는 버그 해결
