### ISSUE TITLE
[FEAT] EC2 재부팅 시 자동으로 self-hosted runner 실행되도록 설정

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#284]
## Description 💭
EC2 재부팅 시 자동으로 self-hosted runner 가 실행되지 않아 수동으로 켜야하는 불편함이 있다.

## TODO ✅
- [ ] prod-a 환경 EC2 재부팅 시 self-hosted runner 자동 실행 설정
- [ ] prod-b 환경 EC2 재부팅 시 self-hosted runner 자동 실행 설정
- [ ] dev 환경 EC2 재부팅 시 self-hosted runner 자동 실행 설정
