### ISSUE TITLE
[FEAT] 라운드 결과 페이지 피드백 반영

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#290]
## Description 💭
라운드 결과 페이지에서 받은 유저 피드백을 개선한다.

## TODO ✅
- [ ] 결과 + 현황을 탭 2개로 수정한다. 
- [ ] 해당 문항에 대한 전체 응답 결과를 결과 탭 하단에 텍스트로 안내한다. 
- [ ] 현황 탭에서 나의 닉네임을 강조한다.
- [ ] 다른 브라우저에 있을 때 다음 게임으로 넘어가서 게임에 참여하지 못한 경우, 게임 끝나기 대기 중 에러 처리한다.
