### ISSUE TITLE
[REFACTOR] 대기방 및 닉네임 화면 성능 개선

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#291]
## Description 💭

대기방 및 닉네임 화면에서 성능 지표가 낮게 나오는 상황이라 성능 개선의 필요성을 느낌 

## TODO ✅
- [x] lazy loading / code splitting <- 이미 다른 PR에서 구현됨
- [x] font 최적화 <- 이미 PR 구현됨  
- [x] Image 확장자 변경 

### Reference 🔎
![image](https://github.com/user-attachments/assets/544a6266-001d-4ed8-9b0b-8b30a174d730)
