### ISSUE TITLE
[REFACTOR] 라운드 결과 & 매칭 결과 성능 개선

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#300]
## Description 💭
라운드 결과, 매칭 결과 

## TODO ✅
- [ ] 이미지 파일 webp 확장자로 수정
- [ ] 레이아웃 시프트 개선
- [ ] 프레임 드랍 개선
- [ ] 애니메이션 최적화
