### ISSUE TITLE
[REFACTOR] 게임 화면 웹 접근성 개선

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#321]
## Description 💭
- 게임 화면 웹 접근성 개선
- 방장이 시작 버튼을 누르면 방의 참여자 모두 함께 게임 페이지로 이동
- 매 라운드 하나의 질문이 주어지고 제한 시간 내에 두 개의 선택지 중 하나를 골라 투표

## TODO ✅
- [x] aria-label, aria-live 적절하게 추가해서 접근성 개선
- [x]  타이머 안내 음성
- [x]  게임 페이지 최초 접속 시 밸런스 게임 질문과 옵션 안내 음성
- [x]  버튼을 클릭했을 때 해당 옵션이 선택되었다는 안내 음성

https://github.com/user-attachments/assets/d4ffccd2-cb62-4b26-b8db-18a4b8fef6f9

### 개선 전
```
📢
2 배너 랜드마크
슬래시
5
밸런스 게임 머리말 레벨 1 앤드 배너
연애
둘 중 한 사람과 사귄다면?
타이머 이미지
영칠(07)
나의 위로 15살 차이에 재산 30억
vs
나이 위아래로 2~3살 차이인데 빚 3억
선택 버튼
```
게임 페이지에 최초 진입 시 밸런스 게임 질문과 옵션 안내 나오면 좋을 것 같다.
옵션을 선택하면 - 옵션이 선택되었다는 안내 나오면 좋을 것 같다.
타이머가 얼마 남지 않았을때 (3초정도) 음성으로 안내 나오면 좋을 것 같다. 

### 개선 후
```
📢
전체 5라운드 중 2라운드
질문 : 둘 중 한 사람과 사귄다면? 옵션 1번. 나의 위로 15살 차이에 재산 30억. 옵션 2번. 나이 위아래로 2~3살 차이인데 빚 3억 (최초 진입 시 질문과 옵션 안내)
(타이머 1초 마다 읽기)
옵션 1
옵션 1 선택 (옵션 버튼 클릭 시)
옵션 2
선택 버튼
옵션 1 선택 완료 (선택 버튼 클릭 시)
```

### Reference 🔎
https://github.com/useon/woowa-writing/blob/technical/technical.md

**Comment by useon** [comment]
어떻게 읽히도록 개선하겠다는 내용도 공유해 주셔용 ~~~! ☺️

**Comment by rbgksqkr** [comment]
추가했습니다 다른 의견 있다면 코멘트해주세용

**Comment by useon** [comment]
혹시 저렇게 다 읽고 나면 몇 초 걸릴까요 ???? 타이머를 또 고려해야 해서 30초로 늘린다고 해도 몇 초가 남을지 궁금하네요.. 너무 타이트 하다면 더 짧게 줄여야 할 것 같아요 !!! 내일 직접 플레이 해 보고 이야기 나눠도 좋을 것 같아요 🤭

**Comment by rbgksqkr** [comment]
앞에 말해준 옵션을 까먹을 수도 있겠네용 한번 구현해보고 다같이 상의해봐도 좋을 것 같아요!!!
