### ISSUE TITLE
[REFACTOR] 대기방 페이지 스크린 리더기 개선

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#322]
## Description 💭

스크린 리더기를 생각하며 개발하지 않아 서비스가 리더기에 적합하지 않은 상황. 

## TODO ✅
- [x] 방 정보 한 번에 읽기 
- [x] 대기방에 참여 중인 멤버가 바뀔 때 바뀐 총 인원 읽어 주기
- [x]  방 정보 변경 시 다시 방 정보 읽음 
- [x] 닉네임 페이지에서 닉네임 Input에 focus 시 `닉네임 입력` 메세지 읽어주기  
- [x] 방 나가기 버튼 클릭 시 확인 modal 
- [x] 아이콘 화질 저하 문제 발생해 확장자 svg로 변경  

## Before

1. 스크린 리더기가 카테고리 박스에 접근 시 구체적인 `방 정보`를 읽지 못함
2. 대기방에 멤버가 들어오거나 나간 경우 변경을 감지하지 못함
3. 방장이 `방 정보` 변경 시 멤버들이 변화를 감지 못함
4. 닉네임 Input에 focus가 되어도 스크린 리더기에서 인지하지 힘든 상황

## After 

1.  스크린 리더기가 `방 설정 컴포넌트`에 접근 시 `타이머`, `카테고리`, `총 인원`을 한 번에 읽는다
2. align-live를 사용해 `총 인원`의 변경을 감지한다
3.  `방 설정 컴포넌트`에 align-live를 사용하여 변경 사항이 있을 경우 감지한다
4. 닉네임 Input에 focus가 되면 `aria-label`을 통해 `닉네임 Input`인 것을 읽는다.

**Comment by useon** [comment]
폼에 ~!! 어떻게 읽히도록 개선할지 미리 공유해 주시면 좋을 것 같아용 😎✨

**Comment by useon** [comment]
확인 ~~~ !!! 일단 하고 다시 이야기 나눕시다 !
