### ISSUE TITLE
[FEAT] 무중단 배포

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#327]
## Description 💭
Nginx를 활용하여 Blue/Green 무중단 배포를 구현한다.

## TODO ✅
- [x] 두 개로 분리되어 있는 CD yml 파일을 하나로 통합
- [x] artifact로 변경
- [x] prod 인스턴스 구축
  - [x] runner 설치
  - [x] Nginx 설치
- [x] 동적 포트 포워딩
- [x] yml의 `server.port` 제거
- [x] Blue/Green 구현
- [x] 롤백 정책 설정
