### ISSUE TITLE
[FEAT] Spring Rest Docs 설정

### ISSUE THREAD

**Issue by GIVEN53** [woowacourse-teams/2024-ddangkong#34]
## Description 💭
api 문서 자동화를 위해 설정을 적용한다.
> snippet customizing은 우선 순위가 낮으므로, 필수인 부분만 먼저 PR을 보낼 예정

논의할 사항
- 생성된 api 문서를 프론트엔드에게 어떤 방식으로 공유할지

## TODO ✅
- [x] build.gradle 설정
- [x] test RestDocumentation 설정
- [x] .adoc 파일 가이드라인
- [x] snippet customizing

### Reference 🔎
https://techblog.woowahan.com/2597/
https://narusas.github.io/2018/03/21/Asciidoc-basic.html
