### ISSUE TITLE
[FIX] 라운드 결과 페이지 버그 개선

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#366]
## Description 💭

- 사용자 피드백에 따라 UI를 수정하면서 생긴 버그 개선

## TODO ✅

- [x] mutation 액션이 발생하는 버튼에 로딩 상태 처리 필요
- [x] 투표 현황 누를 때마다 /content, /vote-result api 계속 호출함
- [x] 투표 현황에서 내 닉네임 진하게 표시 안 됨(쿠키 이후)
- [x] 데스크탑에서 투표 통계 탭 스크롤 발생
- [x] 이미지 화질 확인
