### ISSUE TITLE
[REFACTOR] 닉네임 정책 변경 (2~12자 -> 1자~12자)

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#383]
## Description 💭
닉네임 정책 `2~12자` -> `1~12자` 로 변경

## TODO ✅
- [x] 2자 이상 제한 제거
- [x] 닉네임 정책 `1~12자` 로 변경
- [x] 공백, Null 제한 설정
