### ISSUE TITLE
[FEAT] CI / CD 환경 설정

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#39]
## Description 💭

CI / CD 환경 설정 및 AWS 배포 후 자동화 작업

## TODO ✅
- [x] S3 + cloudfront로 현재 development branch에 있는 React 코드 배포 후 정상 동작 확인
- [x] 위 동작을 Github Actions으로 자동화
- [x] CI (push시 test, build 되는 지 확인 and rebase 자동화)
