### ISSUE TITLE
[FEAT] Discord 웹훅 연결

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#4]
## Description 💭
개발 생산성을 높이기 위해 Discord 웹훅 기능을 통해 Github 웹훅을 연결한다.

## TODO ✅
- [x] PR 관련 알림
- [x] Issue 관련 알림
- [x] Release 관련 알림
- [x] Milestone 관련 알림
- [x] Push 관련 알림
