### ISSUE TITLE
[FEAT] 새로운 AWS 계정에서 Prod 환경 구축

### ISSUE THREAD

**Issue by leegwichan** [woowacourse-teams/2024-ddangkong#415]
## Description 💭

- 우테코 서버 지원 종료로 인해 AWS 이관 작업 필요
- 새로운 AWS 계정에서 Prod 환경 구축 실시

## TODO ✅
- [ ] Prod EC2 환경 구축
  - JDK 17, Node Exporter, ... 
- [ ] RDS 설정
  - 유저 분리, ...
- [ ] CI/CD 설정
  - Nginx를 이용한 Blue/Green 배포 실시  
- [ ] 기존 DB 이관 작업
  - dump 파일을 이용한 DB 이관 작업 진행
- [ ] HTTPS 설정
  - acme.sh를 이용한 HTTPS 설정
  - 일단 설정 후에, 나중에 Route 53 등으로 Front와 같이 쓸 수 있는지 고려할 예정

### Reference 🔎

(작업 중 추가 예정)

**Comment by leegwichan** [comment]
"모니터링 관련 설정" dev 환경에 모니터링 구축 후 실시하도록 하겠습니다.
