### ISSUE TITLE
[FEAT] 새로운 AWS 계정에서 Dev 환경 구축 

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#416]
## Description 💭
우테코 수료에 따라 만료되는 기존 AWS 계정.
새로운 AWS 계정을 생성하여 새 Dev 환경 구축

## TODO ✅
- [x] JDK17 설치
- [x] Swap 메모리 설정
- [x] CI/CD 세팅 (중단 배포) #419 
- [x] HTTPS 설정 및 도메인 연결 [Link](https://pgmjun.tistory.com/183)
- [ ] 모니터링 도구 세팅 (Prometheus, Grafana, Loki)

**Comment by leegwichan** [comment]
GCP 이관으로 Issue Closed 처리함
