### ISSUE TITLE
[FIX] 프론트엔드 코드 리뷰 리마인더 및 Discord 알림 수정

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#432]
## Description 💭
확인을 위해 넣어두었던 PR이 열리면 알람이 오도록 하는 코드, 라벨을 자동으로 달아주는 스크립트가 돌고나서 PR이 올라오는 경우 D-unknown으로 알림이 오는 문제 

## TODO ✅
- [ ] 확인을 위해 넣어두었던 PR이 열리면 알람이 오도록 하는 코드 삭제
- [ ] 라벨을 자동으로 달아주는 스크립트가 돌고나서 PR이 올라오는 경우 D-unknown으로 알림이 오는 문제 D-3으로 수정
- [ ] github action의 schedule이 한 시간이나 딜레이가 되어 시간대 수정
