### ISSUE TITLE
[REFACTOR] Barrel Pattern 적용 

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#439]
## Description 💭

파일들이 많아지면서 최상단에 import 문들이 많아지고 있어 `Barrel Pattern`을 적용해 코드를 읽기 좋게 변경한다. 

### Barrel Parttern이란?
여러 곳에서 export 되고 있는 모듈들을 한 파일에 모아서 한 번에 export하는 방식의 패턴

## TODO ✅
- [x] 각 폴더에 index.ts 생성 후 한 번에 export 하도록 변경
- [x] 이미지 확장자를 `png` -> `webp`로 바꾸면서 사용하지 않게 된 `png` 이미지들 삭제
- [x] hook과 component의 depth를 같게 유지 
기존에는 `hooks` 폴더와 각 컴포넌트가 같은 depth에 있어 어색한 폴더구조라 생각되어 다른 폴더에서와 일관성을 지키기 위해 똑같이 `hooks`, `components` 폴더로 변경
![image](https://github.com/user-attachments/assets/f4a91af2-07b0-4fed-a8df-ef0e183fc75b)

### Before
![image](https://github.com/user-attachments/assets/713f8b0f-525f-4b12-9a00-a7b4be134486)
### After 
![image](https://github.com/user-attachments/assets/9811275f-4629-458a-88af-680ed9a42fd1)

여러 줄에서 import 해 오던 컴포넌트를 한 줄에서 불러올 수 있게 되었다.
