### ISSUE TITLE
[FEAT] 땅콩 서비스 소개

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#440]
## Description 💭
땅콩 사용법이나 소개가 필요할 것 같다는 유저들의 피드백이 많아서 소개 페이지를 추가하려고 한다.

## TODO ✅
- [ ] 메인 페이지 스크롤 시 땅콩 서비스 소개 추가
- [ ] 사용자 초대로 접속 시 바로 닉네임 페이지로 가지 않고 메인 페이지로 가도록 로직 수정
- [ ] 방장 여부에 따라 메인 페이지의 버튼이 방 생성하기 또는 방 참여하기로 나타나도록 로직 수정
