### ISSUE TITLE
[FEAT] 라운드 통계 화면 구현

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#50]
## Description 💭
라운드 통계 화면에서 필요한 기능 구현

## TODO ✅
- [x]  UI 퍼블리싱
- [x]  탭으로 그룹과 전체 선택 데이터 보여주기
- [x]  탭 이동 전에 데이터 불러오기 (캐싱)
- [x]  투표 확인 버튼에 라우팅
