### ISSUE TITLE
[FEAT] msw를 활용하여 mock server 구축

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#6]
## Description 💭
msw 활용하여 mock data로 API 통신 구조 만들기

## TODO ✅
- [x] 질문/대답 데이터 불러오기 get 요청
- [x] 투표 결과 반영 post 요청
- [x] API 요청 구조 설계
