### ISSUE TITLE
[FEAT] 공통 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#60]
## Description 💭
공통 모달 컴포넌트를 구현하여 모달을 재사용할 수 있도록 한다.

## TODO ✅
- [x] 모달 컴포넌트 구현
- [x] 모달 밖 영역 클릭시 모달 닫기 기능
- [x] 모달에서 esc 키를 눌렀을 때 모달 닫기 기능
- [x] 모달 뒤 영역 스크롤 방지 기능
