### ISSUE TITLE
[FEAT] 공통 컴포넌트 및 레이아웃 구현

### ISSUE THREAD

**Issue by useon** [woowacourse-teams/2024-ddangkong#7]
## Description 💭
공통적으로 사용되는 컴포넌트를 추상화하여 구현하고 기본 레이아웃과 글로벌 스타일을 적용한다.

## TODO ✅
- [x] 레이아웃 및 글로벌 스타일 적용
- [x] Header 컴포넌트 구현
- [x] Button 컴포넌트 구현
- [x] TopicContainer 컴포넌트 구현
