### ISSUE TITLE
[TEST] Room API 문서 작성을 위한 테스트 추가

### ISSUE THREAD

**Issue by jhon3242** [woowacourse-teams/2024-ddangkong#85]
## Description 💭
Room API 문서 작성을 위한 테스트 추가

## TODO ✅
- [x] 방 참여 API 테스트 추가
- [x] 방 생성 API 테스트 추가
- [x] 방 전체 멤버 조회 API 테스트 추가
- [x] 다음 라운드로 이동 API 테스트 추가
