### ISSUE TITLE
[FEAT] 방 생성 후 참가 

### ISSUE THREAD

**Issue by novice0840** [woowacourse-teams/2024-ddangkong#92]
## Description 💭

방 생성 후 참가 

## TODO ✅
- [x] 방 만들기 버튼 클릭 후 방장은 닉네임을 설정해서 방을 만들 수 있다
- [x] 방 만들기 버튼을 누르고 닉네임 설정 페이지로 넘어갈 때 방장 여부를 판단하는 값을 넘겨준다.
- [x] 그룹원이 방에 참여하면 닉네임 설정 화면 으로 이동한다
