### ISSUE TITLE
[FEAT] 대기방 정보 조회 API 구현

### ISSUE THREAD

**Issue by PgmJun** [woowacourse-teams/2024-ddangkong#94]
## Description 💭
대기방 멤버 정보 조회 API를 대기방의 정보를 조회하는 API로 변경한다.

## TODO ✅
- [x] Room 엔티티에 방의 상태 Field를 추가한다. (READY, PROGESS, END)
- [x] Room 엔티티에 방의 시간 제한 Field를 추가한다. (Default 10000msec)
- [x] 대기방 멤버 조회 DTO에 방의 게임 시작 여부 데이터를 추가한다.
- [x] 대기방 멤버 조회 DTO에 방의 세팅정보 데이터를 추가한다.

### Reference 🔎
[API 문서](https://www.notion.so/ghenmaru/API-8113194c91fd4d62a0808a01b156628f?pvs=4)
