### ISSUE TITLE
[FEAT] 제한 시간이 끝나거나 투표가 완료되면 라운드 통계 페이지로 라우팅

### ISSUE THREAD

**Issue by rbgksqkr** [woowacourse-teams/2024-ddangkong#97]
## Description 💭
제한 시간이 끝나거나 투표가 완료되었다는 서버에 응답이 오면 라운드 통계 페이지로 라우팅

## TODO ✅
- [x] 클라이언트측에서 제한 시간 카운트
- [x] 제한시간이 끝나거나 투표가 완료되어 게임이 끝났는지 polling으로 서버에 요청
- [x] 게임이 끝났다는 응답이 오면 라운드 통계 페이지로 라우팅
